version: '3'

services:
    flask-app:
        container_name: randomthought
        image: al3xfreeman/randomthought:latest
        restart: always
        environment:
            SECRET_KEY: test 
            DATABASE_URL: mysql+pymysql://randomthought:root@dbserver/randomthought
        depends_on: [dbserver]
        ports:
            - '8000:5000'
        networks:
            - backend
        entrypoint:
            - ./boot.sh

    dbserver:
        container_name: dbserver
        image: mysql/mysql-server
        restart: always
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
            MYSQL_DATABASE: randomthought
            MYSQL_USER: randomthought
            MYSQL_PASSWORD: root
        ports:
            - '3308:3306'
        volumes:
            - database:/var/lib/mysql
        networks:
            - backend

networks:
    backend:

volumes:
    app:
    database: