"""Added view count to posts

Revision ID: 6a11ac32e9ed
Revises: d175eb5f7488
Create Date: 2022-11-06 23:53:27.214561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a11ac32e9ed'
down_revision = 'd175eb5f7488'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('view_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'view_count')
    # ### end Alembic commands ###
