"""Added last_post to Users

Revision ID: d175eb5f7488
Revises: 85003200804c
Create Date: 2022-11-02 15:17:21.954355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd175eb5f7488'
down_revision = '85003200804c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_post', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_post')
    # ### end Alembic commands ###
